$(document).ready(function(){
    $("#burger").hide();
    $("#chinese").hide();
    $("#french").hide();
    $("#indian").hide();
    $("#italian").hide();
    $("#japan").hide();
    $("#latin").hide();
    $("#medi").hide();
    $("#sg").hide();
    $("#sweet").hide();
    $("#thai").hide();
    $("#viet").hide();

    $("#burger-button").click(function(){
        $("#burger").show();
        $("#welcome").hide();
        $("#chinese").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#chinese-button").click(function(){
        $("#chinese").show();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#french-button").click(function(){
        $("#french").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });
    
    $("#indian-button").click(function(){
        $("#indian").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#italian-button").click(function(){
        $("#italian").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#japan-button").click(function(){
        $("#japan").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#latin-button").click(function(){
        $("#latin").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#medi-button").click(function(){
        $("#medi").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#sg-button").click(function(){
        $("#sg").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sweet").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#sweet-button").click(function(){
        $("#sweet").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#thai").hide();
        $("#viet").hide();
    });

    $("#thai-button").click(function(){
        $("#thai").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#viet").hide();
    });

    $("#viet-button").click(function(){
        $("#viet").show();
        $("#chinese").hide();
        $("#burger").hide();
        $("#welcome").hide();
        $("#french").hide();
        $("#indian").hide();
        $("#italian").hide();
        $("#japan").hide();
        $("#latin").hide();
        $("#medi").hide();
        $("#sg").hide();
        $("#sweet").hide();
        $("#thai").hide();
    });
});